### ISSUE TITLE
Conda environments are only allowed with shell, script or wrapper directives (not with run). - preproc.sm", line 27

### ISSUE THREAD

**Issue by spabinger** [pirovc/metameta#1]
Hi,

I installed MetaMeta according to the description on the Github page, but when I try to start the program it fails with the following error:

```
RuleException in line 27 of /home/stephan/work/miniconda/data/opt/metameta/scripts/preproc.sm:
Conda environments are only allowed with shell, script or wrapper directives (not with run).
  File "/home/stephan/work/miniconda/data/opt/metameta/Snakefile", line 24, in <module>
  File "/home/stephan/work/miniconda/data/opt/metameta/scripts/preproc.sm", line 27, in <module>
```

Do you know how to fix it?

Thanks,
Stephan

**Comment by pirovc** [comment]
Hi @spabinger,

Did you run MetaMeta with the _--use-conda_ parameter? 
Is Snakemake on version 3.9.1?
If you are running it with some queuing system (slurm, torque, etc) you will need to pre-install the tools before running MetaMeta (check [README](https://github.com/pirovc/metameta/blob/master/README.md) ).

Best,
Vitor

**Comment by spabinger** [comment]
Hi,

thanks for the fast reply.

- yes, this is my command:
```
metameta --configfile epitype_test.yaml --use-conda --keep-going --cores 32
RuleException in line 27 of /home/stephan/work/miniconda/data/opt/metameta/scripts/preproc.sm:
Conda environments are only allowed with shell, script or wrapper directives (not with run).
  File "/home/stephan/work/miniconda/data/opt/metameta/Snakefile", line 24, in <module>
  File "/home/stephan/work/miniconda/data/opt/metameta/scripts/preproc.sm", line 27, in <module>
```

- Snakemake:
```
snakemake --version
3.12.0
```
- No queuing system

Best,
Stephan

**Comment by pirovc** [comment]
I believe the problem is the Snakemake version. MetaMeta was developed and tested on version 3.9.1 and this is the only version supported by now. I recommend you to downgrade to 3.9.1 via conda (`conda install -c bioconda snakemake=3.9.1`).

If you need the recent version for other applications I recommend to install and run MetaMeta on a separated environment:

```
conda create -c bioconda -n metameta metameta=1.1
source activate metameta
metameta --configfile epitype_test.yaml --use-conda --keep-going --cores 32
source deactivate
```

Please let me know if that solves the problem.
Vitor

**Comment by spabinger** [comment]
Thanks for your help - it's running right now :-)

Best,
Stephan
