### ISSUE TITLE
Convert final metametamerge output files into .biom format

### ISSUE THREAD

**Issue by muslih14** [pirovc/metameta#13]
Hi Vitor,

Is there a way I could convert the final metametamerge.profile.out.detailed file into a .biom file for import into QIIME for analysis?

Best wishes,
Muslih.

**Comment by pirovc** [comment]
Hi Muslih,

Unfortunately there's no such functionality yet. I'll try to add them on a future relase, but no idead when that would happen.

Best,
Vitor
