### ISSUE TITLE
Can't install metameta with conda

### ISSUE THREAD

**Issue by GuoHao150** [pirovc/metameta#19]
I try to install metameta with the commond `conda install metameta=1.2.0` but it just show me `Error: No packages found matching: metameta 1.2|1.2.0*` or `Error: No packages found matching: metameta` 

So how can I install this package properly

**Comment by pirovc** [comment]
Hi @GuoHao150 

I think you do not have the proper channels configured. You can add the channels to your conda installation with:

```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```
or use it only for installing metameta:

`conda install -c bioconda -c conda-forge metameta=1.2.0`

Metameta has several dependencies so I recommend creating a separated environment for it with the command:

`conda create -n metameta_env -c bioconda -c conda-forge metameta=1.2.0`

Please let me know if that solves the issue.

Vitor

**Comment by GuoHao150** [comment]
Yeah,it works with the command `conda create -n metameta_env -c bioconda -c conda-forge metameta=1.2.0` and turns out my previous faliure was caused by old version of conda. Thanks bro
