### ISSUE TITLE
Can't download the pre-config database

### ISSUE THREAD

**Issue by GuoHao150** [pirovc/metameta#20]
I try to reproduce the result of sample data after installed the metameta with the command you provided and there are some error when the programme download the pre-config database

```
RuleException:
CalledProcessError in line 15 of /anaconda3/envs/metameta/opt/metameta/scripts/preconfigdb.sm:
Command '  curl -L -o /some_tests/metameta/databasearchaea_bacteria_201503/kaiju.tar.gz https://zenodo.org/record/819425/files/kaiju_bac_arc_v1.tar.gz > /some_tests/metameta/databasearchaea_bacteria_201503/log/kaiju_db_archaea_bacteria_201503_download.log 2>&1 ' returned non-zero exit status 18.
  File "/anaconda3/envs/metameta/opt/metameta/scripts/preconfigdb.sm", line 15, in __rule_preconfigdb_download
  File "/anaconda3/envs/metameta/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Exiting because a job execution failed. Look above for error message
```

So I tried to download the database with the command
`wget -c  https://zenodo.org/record/819425/files/kaiju_bac_arc_v1.tar.gz` but it return this `Unable to establish SSL connection.` so does the clark_bac_arc_v1.tar.gz...

Is there any alternative way to download the pre-config database

Thanks

**Comment by pirovc** [comment]
Looks like zenodo is unavailable for the time being. Please try again later once they are back up.

![image](https://user-images.githubusercontent.com/4673375/79424852-1a9af500-7fc1-11ea-9497-a076844124f6.png)

**Comment by GuoHao150** [comment]
I'll try to run the programme later. Thanks for your help
