### ISSUE TITLE
Combining output from samples?

### ISSUE THREAD

**Issue by Thomieh73** [pirovc/metameta#6]
Hey Vitor,

this is a general question. After running metameta, I get for each sample a metameta profile. I am not sure if I have missed in the the set-up of the yaml file, but is there a way to combine the profile files for each sample into one big tabular file? Or is that not implemented in the metameta workflow?

Best
Thomas

**Comment by pirovc** [comment]
Hi Thomas,

This functionality is not implemented directly to MetaMeta but I added a extra script that can help you with it under scripts/merge_final_profiles.sh

Arguments are the final profiles in the BioBoxes format. For example:
`./merge_final_profiles.sh workdir/sample_*/metametamerge/archaea_bacteria/final.metametamerge.profile.out`
or
`./merge_final_profiles.sh sample1.profile.out sample2.profile.out sample3.profile.out`

Best,
Vitor

**Comment by Thomieh73** [comment]
Hey Vitor,
I tried the script and it works perfectly. 
Thanks for adding te script. 

Enjoy the weekend.
