### ISSUE TITLE
Built in database refseq version

### ISSUE THREAD

**Issue by muslih14** [pirovc/metameta#9]
Hi Pirovc,

Can I know which version of the Refseq database you used to compose the built-in bacterial archeal database?

**Comment by pirovc** [comment]
Hi @muslih14 

The default database (archaea and bacteria) are in general from mid 2015. Here you can find a description for each one of them:
CLARK (https://doi.org/10.5281/zenodo.819305)
DUDes (https://doi.org/10.5281/zenodo.819343)
GOTTCHA (https://doi.org/10.5281/zenodo.819341)
kaiju (https://doi.org/10.5281/zenodo.819425)
kraken (https://doi.org/10.5281/zenodo.819363)
mOTUs (https://doi.org/10.5281/zenodo.819365)

I plan to upload and make it available in the next release an updated version of them and also a Viral and Fungal default database. 

Vitor

**Comment by muslih14** [comment]
Thank you, Vitor.

Looking forward to the updated database in the next version

Cheers,
Muslih.
